### ISSUE TITLE
Error with ros while building the docker Image.

### ISSUE THREAD

**Issue by mhamedLmarbouh** [PRBonn/bonnetal#3]
after running:
`nvidia-docker build -t tano297/bonnetal:base -f docker/base/Dockerfile .`

I get the following Error message:
`Err:12 http://packages.ros.org/ros/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654`
`Reading package lists...`
`W: GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654`
`E: The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed.`

**Comment by tano297** [comment]
0ab883b8356954c3e57a07a73c30bbac8f035a05 Should fix this.
