### ISSUE TITLE
Cannot download pretrained models 

### ISSUE THREAD

**Issue by Alex-Beh** [PRBonn/bonnetal#30]
Do [pretrained models](https://github.com/PRBonn/bonnetal#pre-trained-models) available to public?

**Comment by jbehley** [comment]
When I check the links then they are working for me. Is there a specific model that doesn't work downloading for you?

**Comment by Alex-Beh** [comment]
Hi, I managed to download the file using firefox instead of google chrome... although I have enabled the pop up notification already... But there is no model.pytorch or model.trt in the file. May I know is this normal? Any steps I've missed out?
